version: '3'

services:
  database:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: snowtricks_db
      MYSQL_USER: usersnowtricks
      MYSQL_PASSWORD: passwordsnowtricks
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
    - ./database:/var/lib/mysql
    networks:
      - symfony

  nginx:
    build:
      context: ./nginx
    ports:
    - "8000:80"
    depends_on:
      - php
    volumes:
    - ./symfony:/app/
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./logs:/var/log/nginx/
    networks:
      - symfony

  php:
    build:
      context: ./php-fpm
    depends_on:
      - database
    volumes:
    - ./symfony:/app
    networks:
      - symfony

  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    ports:
      - 25:25
      - "8002:80"
    networks:
      - symfony

networks:
  symfony: